name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - run: npm ci
      - run: npm run build
      - run: npm run package

      - name: Checksums
        run: |
          shasum -a 256 bin/sniptt-linux >> CHECKSUMS.md
          shasum -a 256 bin/sniptt-macos >> CHECKSUMS.md

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true 
          body_path: CHECKSUMS.md
          files: |
            LICENSE
            bin/sniptt-linux
            bin/sniptt-macos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
